sqlite: &development
  adapter: postgresql
  database: roomr_development
  username: "<%=ENV['POSTGRES_USERNAME']%>"
  password: "<%=ENV['POSTGRES_PASSWORD']%>"

mysql: &mysql
  adapter: mysql2
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  username: "<%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>"
  password: "<%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>"
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>

postgresql: &postgresql
  adapter: postgresql
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
  min_messages: ERROR
  reconnect: false

defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8
  <<: *<%= ENV['RAILS_DB'] || "development" %>

development:
  <<: *defaults

test: &test
  <<: *defaults

production:
  <<: *defaults
